# Generated by Django 4.2 on 2023-04-09 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outbound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=8)),
                ('outbound_quantity', models.IntegerField()),
                ('outbound_date', models.DateField()),
                ('outbound_cost', models.IntegerField()),
            ],
        ),
    ]
